name: Create PR from main to prod

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual trigger

jobs:
  create-prod-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Fetch all branches
        run: git fetch origin
      
      - name: Check if prod branch exists and has differences
        id: check
        run: |
          # Check if prod branch exists
          if git rev-parse --verify origin/prod >/dev/null 2>&1; then
            # Branch exists, check for differences
            if git diff --quiet origin/prod origin/main; then
              echo "changes=false" >> $GITHUB_OUTPUT
              echo "branch_exists=true" >> $GITHUB_OUTPUT
            else
              echo "changes=true" >> $GITHUB_OUTPUT
              echo "branch_exists=true" >> $GITHUB_OUTPUT
            fi
          else
            # Branch doesn't exist, create it
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request from main to prod
        if: steps.check.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head main \
            --base prod \
            --title "🚀 Deploy main changes to prod" \
            --body "## Main to Prod Deployment

          This PR contains the latest changes from the main branch ready for production deployment.

          **Changes included:**
          - Latest commits from main branch
          - Auto-generated by main-to-prod deployment workflow

          **What this means:**
          - Your main branch has new changes ready for production
          - This PR will deploy those changes to the prod branch
          - Review carefully before merging to production

          **Review checklist:**
          - [ ] Verify all changes are production-ready
          - [ ] Check that all tests are passing
          - [ ] Ensure no breaking changes are included
          - [ ] Confirm deployment readiness

          ---
          *This PR was automatically created by the main-to-prod deployment workflow*"
