name: Sync with upstream
on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Add upstream remote
        run: git remote add upstream https://github.com/supabase/realtime
      
      - name: Fetch upstream and origin
        run: |
          git fetch upstream
          git fetch origin
      
      - name: Check for changes
        id: check
        run: |
          # Check if upstream branch exists and compare, otherwise compare with HEAD
          if git rev-parse --verify origin/upstream >/dev/null 2>&1; then
            if git diff --quiet origin/upstream upstream/main; then
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          else
            # First time running, upstream branch doesn't exist yet
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Sync if changes exist
        if: steps.check.outputs.changes == 'true'
        run: |
          git checkout -B upstream
          git merge upstream/main
          git push origin upstream