name: Sync with upstream

on:
  schedule:
    - cron: '0 6 * * *'  # Run daily at 6 AM UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: repo-sync
        id: sync
        uses: repo-sync/github-sync@7c8493e95237362ad417495e8512c37e78d25f19
        with:
          source_repo: "https://github.com/supabase/realtime"
          source_branch: "main"
          destination_branch: "upstream"
          sync_tags: ""
          token: ${{ secrets.UNITY_PAT }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: upstream
          base: main
          title: "🔄 Sync with upstream changes"
          body: |
            ## Upstream Sync
            
            This PR contains the latest changes from the upstream repository.
            
            **Changes included:**
            - Synced from upstream/main
            - Auto-generated by upstream sync workflow
            
            **Review checklist:**
            - [ ] Review the changes for any breaking changes
            - [ ] Check for conflicts with local modifications
            - [ ] Verify tests pass (if applicable)
            
            ---
            *This PR was automatically created by the upstream sync workflow*
          draft: false